services:
  cache:
    container_name: "cache"
    image: "docker.io/library/redis:7.4"
    ports:
    - target: 6379
      published: 6379
    restart: unless-stopped
  mongo:
    container_name: "mongo"
    image: "docker.io/library/mongo:8.0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "gbt5Szqa8WD1U9iS4mpCGR"
    ports:
    - target: 27017
      published: 27017
    restart: unless-stopped
  apiservice:
    container_name: "apiservice"
    image: "apiservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__scoutroute: "mongodb://admin:gbt5Szqa8WD1U9iS4mpCGR@mongo:27017/scoutroute?authSource=admin&authMechanism=SCRAM-SHA-256"
      ConnectionStrings__cache: "cache:6379"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
