/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ScoutRoute.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
}
