/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ScoutRoute.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Money } from "./money";

export interface RegisterPaymentCommand {
  id: string;
  /** @nullable */
  message?: string | null;
  amount: Money;
  received: string;
}
