/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ScoutRoute.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PaymentDto {
  id: string;
  /** @nullable */
  message: string | null;
  amount: number;
  received: string;
  /** @nullable */
  addressId: string | null;
  isCompleted: boolean;
}
