/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ScoutRoute.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ListProjectDto } from "./listProjectDto";

export interface ProjectQueryResult {
  projects: ListProjectDto[];
}
