/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ScoutRoute.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { StopDto } from "./stopDto";

export interface RouteDto {
  id: string;
  name: string;
  stops: StopDto[];
  extraStops: number;
  status: number;
  comments: string[];
}
