/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ScoutRoute.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ContactPerson } from "./contactPerson";

export interface StopDto {
  id: string;
  contactPerson: ContactPerson;
  title: string;
  quantity: number;
  comment: string;
  /** @nullable */
  routeId: string | null;
  coordinates: number[];
  status: number;
}
